### ISSUE TITLE
offset html anchors for fixed header 

### ISSUE THREAD

**Issue by deanbot** [deanbot/spiritedrefactor-site#21]
[ref](http://darktef.github.io/posts/2017-03-offset-html-anchors-for-fixed-header-with-css): 

```css
:target {
  display: block;
  position: relative;
  top: -120px; 
  visibility: hidden;
}
````
